apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-controlplane
spec:
  nodeReuse: {{ .Values.machines.nodeReuse }}
  template:
    spec:
      automatedCleaningMode: metadata
      hostSelector:
      {{- toYaml .Values.machines.controlPlane.hostSelector  | nindent 8}}
      dataTemplate:
        name: {{ .Values.cluster.name }}-controlplane-template
      image:
        checksum: {{ .Values.machines.image.checksum.url | replace "${version}" .Values.kubernetes.version }}
        checksumType: {{ .Values.machines.image.checksum.type }}
        format: {{ .Values.machines.image.format }}
        url: {{ .Values.machines.image.url | replace "${version}" .Values.kubernetes.version }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-workers
spec:
  nodeReuse: {{ .Values.machines.nodeReuse }}
  template:
    spec:
      automatedCleaningMode: metadata
      hostSelector: 
      {{- toYaml .Values.machines.workers.hostSelector  | nindent 8}}
      dataTemplate:
        name: {{ .Values.cluster.name }}-workers-template
      image:
        checksum: {{ .Values.machines.image.checksum.url | replace "${version}" .Values.kubernetes.version }}
        checksumType: {{ .Values.machines.image.checksum.type }}
        format: {{ .Values.machines.image.format }}
        url: {{ .Values.machines.image.url | replace "${version}" .Values.kubernetes.version }}
