{{- if .Values.proxmoxWorkers.enabled }}
{{- range $key, $node := .Values.proxmoxWorkers.nodes }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ProxmoxMachineTemplate
metadata:
  {{- $specs := $.Values.proxmoxWorkers.templateSpecs | deepCopy -}}
  {{- $override := $node.specsOverride -}}
  {{- $merged := merge $override $specs  -}}
  {{- $hash := $merged | toYaml | sha256sum | trunc 10 -}}
  name: {{ $.Values.cluster.name }}-proxmox-worker-{{ $node.name }}-{{ $.Values.kubernetes.version }}-{{ $hash }}
spec:
  template:
    spec: {{ $merged | toYaml | nindent 6 }}
      templateSelector:
        matchPolicy: bestSubset
        matchTags:
        - {{ $node.name }}
        - {{ $.Values.kubernetes.version }}
      allowedNodes:
        - {{ $node.name }}
---
{{- end }}
{{- end }}
