namespace: 
  name: clusters
  create: false
  # labels:
  #   app: kubeadm
cluster:
  name: kubeadm
  labels: {}
  networks:
    pods:
      cidrBlocks:
        - 10.40.0.0/18
    services:
      cidrBlocks:
        - 10.96.0.0/12
kubernetes:
  version: v1.32.1

controlPlane:
  infrastructureType: Metal3MachineTemplate
  infrastructureAPIVersion: infrastructure.cluster.x-k8s.io/v1beta2
  skipKubeProxy: false
  schedulable: false
  scaleIn: true
  certificatesExpiryDays: 21
  maxSurge: 0
  loadbalancer:
    kubevip: 
      enabled: true
      image: 
        name: ghcr.io/kube-vip/kube-vip
        tag: latest
  endpoint:
    host: 0.0.0.0/0
    port: 6443
    interface: eno1
  apiServer:
    extrArgs: []
  replicas: 1
  files: []
  mounts: []
  diskSetup: {}
  postKubeadmCommands: []

workers:
  replicas: 0
  files: []
  mounts: []
  diskSetup: {}

# Must deploy relevant proxmox credentials secret in target namespace
# Very opinionated but maybe a useful guide. 
proxmoxWorkers:
  enabled: false
  # Must be set for this deployment as control plane can currently
  # not be managed by the proxmox provider due to limitations in the 
  # template system.
  externalManagedControlPlane: true
  nodes: {} # List of object. Will Create one machine deployment for each node due to template limitations
  #- name: node-name
  #  replicas: no-of-replicas
  #  specsOverride:
  #    memoryMiB: 1239234
  dnsServers: []
  ipam: 
    addresses: []
    gateway: ""
    prefix: 0
  templateTags: [] # Currently not implemented
  templateSpecs: {} #Proxmox machine template spec.template.spec values.
  credentialsRef: ""
  schedulerHints: {}

machines:
  nodepool: nodepool0
  nodeReuse: true
  image:
    # NOTE: both url's can be templated with the .Values.kubernetes.version field by placing
    # ${version} where you want the version to be in the url. This helps prevent incorrect version
    # deployment.
    checksum: 
      url: ""
      type: sha256
    format: qcow2
    url: ""
  controlPlane:
    hostSelector:
      matchLabels:
        role: control-plane
  workers:
    hostSelector:
      matchLabels:
        role: worker
  
cloudInit:
  users: []
    #- name: user
    #  sshAuthorizedKeys:
    #  - <ssh key>
    #  sudo: ALL=(ALL) NOPASSWD:ALL
  mounts: []
  diskSetup: {}
    #filesystems: []
    #partitions: []
